module.exports = {
  territories: [
    { name: 'Northwest', code: 'NW' },
    { name: 'Southeast', code: 'SE' },
    { name: 'Midwest', code: 'MW' },
  ],
  salesReps: [
    { name: 'Meredith Grey', email: 'meredith.grey@example.com', territoryCode: 'NW' },
    { name: 'Derek Shepherd', email: 'derek.shepherd@example.com', territoryCode: 'SE' },
    { name: 'Miranda Bailey', email: 'miranda.bailey@example.com', territoryCode: 'MW' },
  ],
  hcps: [
    { name: 'Dr. Cristina Yang', areaTag: 'Seattle Grace - Cardio', specialty: 'Cardiothoracic Surgery', phone: '206-555-0111', email: 'cristina.yang@example.com' },
    { name: 'Dr. Alex Karev', areaTag: 'Seattle Grace - Peds', specialty: 'Pediatric Surgery', phone: '206-555-0112', email: 'alex.karev@example.com' },
    { name: 'Dr. Arizona Robbins', areaTag: 'Seattle Grace - Peds', specialty: 'Pediatric Surgery', phone: '206-555-0113', email: 'arizona.robbins@example.com' },
    { name: 'Dr. April Kepner', areaTag: 'Seattle Grace - Trauma', specialty: 'Trauma Surgery', phone: '206-555-0114', email: 'april.kepner@example.com' },
    { name: 'Dr. Amelia Shepherd', areaTag: 'Pacific Wellness - Neuro', specialty: 'Neurosurgery', phone: '503-555-0115', email: 'amelia.shepherd@example.com' },
  ],
  visits: [
    {
      visitDate: '2024-05-02',
      status: 'completed',
      durationMinutes: 45,
      repName: 'Meredith Grey',
      hcpName: 'Dr. Cristina Yang',
      hcpAreaTag: 'Seattle Grace - Cardio',
      territoryCode: 'NW',
      notes: 'Follow-up on cardio device adoption.',
    },
    {
      visitDate: '2024-05-05',
      status: 'scheduled',
      durationMinutes: 30,
      repName: 'Meredith Grey',
      hcpName: 'Dr. Alex Karev',
      hcpAreaTag: 'Seattle Grace - Peds',
      territoryCode: 'NW',
      notes: 'Discuss pediatric pilot program.',
    },
    {
      visitDate: '2024-04-28',
      status: 'completed',
      durationMinutes: 60,
      repName: 'Derek Shepherd',
      hcpName: 'Dr. Amelia Shepherd',
      hcpAreaTag: 'Pacific Wellness - Neuro',
      territoryCode: 'SE',
      notes: 'Neurosurgery equipment training.',
    },
    {
      visitDate: '2024-04-30',
      status: 'cancelled',
      durationMinutes: 0,
      repName: 'Miranda Bailey',
      hcpName: 'Dr. April Kepner',
      hcpAreaTag: 'Seattle Grace - Trauma',
      territoryCode: 'MW',
      notes: 'HCP rescheduled due to emergency surgery.',
    },
    {
      visitDate: '2024-05-08',
      status: 'completed',
      durationMinutes: 50,
      repName: 'Miranda Bailey',
      hcpName: 'Dr. Arizona Robbins',
      hcpAreaTag: 'Seattle Grace - Peds',
      territoryCode: 'MW',
      notes: 'Reviewed outcomes from last trial.',
    },
  ],
};
